[package]
name = "evmfetch"
version = "0.1.1"
edition = "2021"

[dependencies]
reqwest = "0.11"
clap = "3.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"