name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --release
    - name: Create tarball
      run: tar -czvf evmfetch-rs.tar.gz -C target/release evmfetch
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: evmfetch-rs
        path: evmfetch-rs.tar.gz